import "../globals.css";
import { Roboto } from "next/font/google";
import Providers from "../providers/Providers";
import Nav from "./components/nav/Nav";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modals,
}: {
  children: React.ReactNode;
  modals: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Nav />
          {children}
          {modals}
        </Providers>
      </body>
    </html>
  );
}
